config/routes.rb
FinalProject::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'products#index', :as => :home

  match 'search_results' => 'products#search_results', :as =>'search_results', :via => :post
  match 'about' => 'contact#index', :as => :contact, :via => :get
  match 'product/:id' => 'products#show', :as => :single_product, :via => :get
  match 'cart/:id/add' => "products#add_to_cart", :as => "add_to_cart", :via => :post
  match 'cart/:id/remove' => "products#remove_from_cart", :as => "remove_from_cart", :via => :post
  match 'cart' => "products#cart", :as => "cart", :via => :get
  match 'cart/empty' => "products#empty_cart", as: "empty_cart", :via => :post
  match 'cart/checkout' => "products#checkout", as: "checkout", :via => :post
  match 'order' => "products#order", as: "order", :via => :post

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name

	has_many :products

	validates :name, :presence => true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :description, :email, :name, :phone
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :address, :city, :country, :email, :first_name, :last_name, :postal_code, :province_id

	has_many :orders
	belongs_to :province

	validates :first_name, :last_name, :address, :city, :postal_code, :email, :country, :province_id, :presence => true
  
  def name
  	return self.first_name + " " + self.last_name 
  end 
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	attr_accessible :order_id, :price, :product_id, :quantity

	belongs_to :order
	belongs_to :product

	validates :quantity, :product_id, :order_id, :price, :presence => true
	validates :price, :quantity, :numericality => true
  
end

app/models/order.rb
class Order < ActiveRecord::Base
	attr_accessible :customer_id, :gst_rate, :hst_rate, :pst_rate, :status

	has_many :line_items
	has_many :products, through: :line_items
	belongs_to :customer

  validates :customer_id, :status, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	attr_accessible :category_id, :description, :image_filename, :name, :price, :stock_quantity

	has_many :line_items
	has_many :orders, through: :line_items
	belongs_to :category

	validates :name, :category, :price, :stock_quantity, :presence => true
	validates :price,:stock_quantity, :numericality => true
 
end

app/models/province.rb
class Province < ActiveRecord::Base
	attr_accessible :gst_rate, :hst_rate, :name, :pst_rate

	has_many :customers

  validates :name, :gst_rate, :pst_rate, :hst_rate, :presence => true
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index
		@contacts = Contact.all
		@contact = @contacts.first
		@search   = Product.search(params[:q])
	end

	def search
	end

	def search_results
		@products = Product.where("name LIKE ? OR description LIKE ?", "%#{params[:keywords]}%", "%#{params[:keywords]}%")
		@products = @products.where("category_id = ?", params[:category]) unless params[:category] == ""
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :initialize_cart

	def index
		@products = Product.order(:created_at)
		@search   = Product.search(params[:q])	
	end

	def show
    @product = Product.find(params[:id])
	end

	def search
	end

	def search_results
		@products = Product.where("name LIKE ? OR description LIKE ?", "%#{params[:keywords]}%", "%#{params[:keywords]}%")
		@products = @products.where("category_id = ?", params[:category]) unless params[:category] == ""
	end

	def cart
	end

	def checkout
	end

	def add_to_cart
		id = params[:id].to_i
		session[:cart] << id unless session[:cart].include?(id)
		redirect_to action: :cart
	end

	def remove_from_cart
		id = params[:id].to_i
		session[:cart].delete(id)
		flash[:message] = "Item Removed"
		redirect_to action: :cart
	end

	def empty_cart
		session[:cart] = []
		@cart_contents = []
		redirect_to action: :index
	end

	def order
		if params[:province] == ""
			province = ""
		else
			province = Province.where("name = '" + params[:province] + "'").first
			province_id = province.id
			@gst = province.gst_rate
			@pst = province.pst_rate
			@hst = province.hst_rate
		end

		@customer = Customer.new(
			first_name: params[:first_name],
			last_name: params[:last_name],
			email: params[:email],
			address: params[:address],
			city: params[:city],
			province_id: province_id,
			country: "Canada",
			postal_code: params[:postal_code]
			)

		@itWorked = false
		@itWorked = @customer.save

		if @itWorked
			@order = @customer.orders.build(
				gst_rate: @gst,
				hst_rate: @hst,
				pst_rate: @pst,
				status: "Unshipped"
				)

			@order.save

			@subtotal = 0.00
			multiplier = @gst + @pst + @hst + 1

			@order_details = @cart_contents

			@order_details.each do |id|
				line_item = @order.line_items.build
				line_item.product = Product.find(id)
				line_item.price = id.price
				line_item.quantity = 1
				line_item.save

				@subtotal += line_item.price
			end

			@total = @subtotal * multiplier
			@cart_contents = []
			session[:cart] = []
		end
	end

protected
	def initialize_cart
		session[:cart] ||=[]
		@cart_contents ||=[]
		@total = 0.00
		session[:cart].each {|id| @cart_contents << Product.find(id) }
		@cart_contents.each do |product|
			@total += product.price
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contact/_contact.html.erb
<section class="contact">

	<p class="description">
		<%= contact.description %>
	</p>

	<div class="contactInfo">

	</div>

</section>

app/views/contact/_search.html.erb
<%=  form_tag search_results_path do %>
  <%= text_field_tag :keywords %>

  <%= select_tag(:category, options_from_collection_for_select(Category.all, :id, :name), {:prompt => 'Choose Category'}) %>

  <%= submit_tag 'Search' %>

<% end %>

app/views/contact/index.html.erb
<section class="contact">

	<p class="description">
		<%= @contact.description %>
	</p>

	<div class="contactInfo">
		<p>Name: <%= @contact.name %> <br />
			Phone: <%= @contact.phone %><br />
			Address: <%= @contact.address %></p>
	</div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turn the Page</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>
	<header>
		<h1>Turn The Page</h1>

		<div class="search">
			<%= render 'search' %>
		</div>

		<nav>
			<ul>
				<li><%= link_to 'Home', home_path %></li>
				<li><%= link_to 'Cart', cart_path %></li>
				<li><%= link_to "About Us", contact_path %></li>	
			</ul>
		</nav>
	</header>
	

<%= yield %>

  <footer>
  	<nav>
	  <ul>
		  <li><%= link_to 'Home', home_path %></li>
		  <li><%= link_to 'Cart', cart_path %></li>
		  <li><%= link_to "About Us", contact_path %></li>	
		</ul>
	</nav>
  </footer>

</body>

</html>

app/views/products/_product.html.erb
<div class="product">
  
  <p class="name">
    <%= link_to product.name, single_product_path(product) %>
  </p>

  <% if product.image_filename != '' %> 
    <p class="image">
      <%= image_tag product.image_filename, {height: 150} %>
    </p>
  <% else %>
    <div class="no_image">
      <p>No Image Available.</p>  
    </div>
  <% end %>

  <p class="price">
    <strong>Price:</strong> <%= number_to_currency product.price %>
  </p>

  <% if product.category %>
    <p>
      <strong>Category:</strong> <%= product.category.name %>
    </p>
  <% end %>

  <%= render partial: "shopping", :locals => {:product => product} %>
  
</div>

app/views/products/_shopping.html.erb
<% if session[:cart].include?(product.id) %>
	<%= button_to "Remove from Cart", remove_from_cart_path(product) %>
<% else %>
	<%= button_to "Add to Cart", add_to_cart_path(product) %>
<% end %>

app/views/products/cart.html.erb
<div id="cart">
	<div class="flash"><h4><%= flash.now[:message] %></h4></div>
	<h1>CART</h1>
  <% if session[:cart].empty? %>
  	<h3>Your cart is empty.</h3>
  	<% else %>
  		<% @cart_contents.each do |product| %>
  			<div class="cartproduct">
  				<h3><%= product.name %></h3>
  				<%= image_tag(product.image_filename, width: 100) %>
  				<p><strong>Qty: 1</strong></p>
  				<p><strong>Price: </strong><%= number_to_currency product.price %></p>
  				<%= render partial: "shopping", :locals => {:product => product} %>
  			</div>
  		<% end %>
	<% end %>
	<div id="buttons">
		<h3>Subtotal: <%= number_to_currency @total %></h3>

    <ul class="cartoptions">
      <li><%= button_to 'Return to Store', home_path %></li>
      <li><%= button_to 'Empty Cart', empty_cart_path unless session[:cart] == [] %></li>
      <li><%= button_to 'Checkout', checkout_path unless session[:cart] == [] %></li>
    </ul>
	</div>
</div>

app/views/products/checkout.html.erb
<h1>CHECKOUT</h1>

<p>Enter your information below:</p>

<%= form_tag(order_path) do %>
  <ul>
  	<li>
	  <%= label_tag(:first_name, "First name:") %>
	  <%= text_field_tag(:first_name) %>
  	</li>
  	<li>
	  <%= label_tag(:last_name, "Last name:") %>
	  <%= text_field_tag(:last_name) %>
  	</li>
  	<li>
	  <%= label_tag(:address, "Address:") %>
	  <%= text_field_tag(:address) %>
  	</li>
  	<li>
	  <%= label_tag(:city, "City:") %>
	  <%= text_field_tag(:city) %>
  	</li>
  	<li>
	  <%= label_tag(:province, "Province:") %>
	  <%= text_field_tag(:province) %>
  	</li>
  	<li>
	  <%= label_tag(:postal_code, "Postal Code:") %>
	  <%= text_field_tag(:postal_code) %>
  	</li>
  	<li>
	  <%= label_tag(:email, "Email:") %>
	  <%= text_field_tag(:email) %>
  	</li>
  </ul>
  <input type="submit" value="Create Order" class="buttons">
<% end %>

app/views/products/index.html.erb
<%= render @products %>

app/views/products/order.html.erb
<% if @itWorked %>

  <h2>Your order has been placed</h2>
  <h3>INVOICE</h3>

  <% @order_details.each do |item|  %>
    <h4>Item: <%= item.name %></h4>
	<p>Quantity: 1 ~ Price: <%= item.price %></p>
  <% end %>

  <h4>Subtotal: <%= number_to_currency @subtotal %></h4>
  <% if @gst > 0.01 %>
    <p>GST: <%= number_to_currency (@gst * @subtotal) %></p>
  <% end %>
  <% if @pst > 0.01 %>
    <p>GST: <%= number_to_currency (@pst * @subtotal) %></p>
  <% end %>
  <% if @hst > 0.01 %>
    <p>GST: <%= number_to_currency (@hst * @subtotal) %></p>
  <% end %>
  <h4>Order Total: <%= number_to_currency @total %></h4>
  <p>Status: <%= @order.status %></p>

  <% else %>
    <p>Error with contact details. Please ensure you have properly filled them all out.</p>
    <%= button_to 'Return to Store', home_path %>
<% end %>

app/views/products/search_results.html.erb
<% if @products.empty? %>
	<p>Your search for "<%= params[:keywords] %>" is bad and you should feel bad.</p>
<% elsif params[:keywords].length < 2 %>
	<p>Please enter at least one full word.</p>
<% else %>
	<%= render @products %>
<% end %>

app/views/products/show.html.erb
<%= render @product %>

  <div class="description">
    <%= @product.description %>
  </div>

<%= link_to 'Back', home_path %>